name: alams ci
on:
  push:
    branches: [ main ]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: say hello to my cohort 6
       run: |
         echo "hello from cohort 6"
         echo "how is the training so far"
